# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/iseung-won/AI_inference_video_player/AI_inference_video_player.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AI_inference_video_player(object):
    def setupUi(self, AI_inference_video_player):
        AI_inference_video_player.setObjectName("AI_inference_video_player")
        AI_inference_video_player.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(AI_inference_video_player)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(490, 80, 103, 32))
        self.comboBox.setObjectName("comboBox")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(40, 70, 640, 480))
        self.openGLWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.openGLWidget.setObjectName("openGLWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 10, 100, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 10, 100, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 10, 100, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(490, 10, 100, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        AI_inference_video_player.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AI_inference_video_player)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        AI_inference_video_player.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AI_inference_video_player)
        self.statusbar.setObjectName("statusbar")
        AI_inference_video_player.setStatusBar(self.statusbar)

        self.retranslateUi(AI_inference_video_player)
        QtCore.QMetaObject.connectSlotsByName(AI_inference_video_player)

    def retranslateUi(self, AI_inference_video_player):
        _translate = QtCore.QCoreApplication.translate
        AI_inference_video_player.setWindowTitle(_translate("AI_inference_video_player", "MainWindow"))
        self.pushButton.setText(_translate("AI_inference_video_player", "play"))
        self.pushButton_2.setText(_translate("AI_inference_video_player", "pause"))
        self.pushButton_3.setText(_translate("AI_inference_video_player", "stop"))
        self.pushButton_4.setText(_translate("AI_inference_video_player", "video_path"))
